# Generated by Django 5.2.1 on 2025-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site_created', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_time',
        ),
    ]
